apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis-master-deployment
  namespace: mlpredict
  labels:
    app: redis
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: redis
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
