apiVersion: v1
kind: Service
metadata:
  name: predictapi-service
  namespace: mlpredict
spec:
  selector:
    app: predictapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
